---
- name: Install virtualisation packages
  ansible.builtin.package:
    name: "{{ item }}"
    state: present
  with_items: "{{ virt_packages }}"

- name: Start and enable libvirtd
  service:
    name: libvirtd
    state: started
    enabled: yes
 
