---
- name: Install virtualisation packages
  ansible.builtin.package:
    name: "{{ item }}"
    state: present
  with_items: "{{ virt_packages }}"

- name: Start and enable libvirtd
  service:
    name: libvirtd
    state: started
    enabled: yes

- name: Add users to libvirt group
  user: 
    name: "{{ item }}"
    groups: libvirt
    append: yes
  with_items:
    - "{{ libvirt_rw_users | default([]) }}"
